### ISSUE TITLE
Click in the notification button

### ISSUE THREAD

**Issue by efrapp** [Nazeh/facebook-replica#7]
Steps to reproduce the error:
- Create two users
- User A sends a friend request to B
- User A cancel the request (to inspect behavior in the console)
- User A sends again friend request to B
- User B clicks on the notification button

<img width="1033" alt="Screen Shot 2019-09-17 at 5 13 05 PM" src="https://user-images.githubusercontent.com/698811/65084056-c74fbe00-d96f-11e9-826a-ba7d0f08b050.png">

**Comment by Nazeh** [comment]
Good morning @efrapp, Thanks a lot for reporting this, unfortunately, I cannot reproduce this error.
Here is what I did in detail:
- Sign up two users
- Log in for the two users on a normal and private window.
- User A finds User B in the explore tab and send them a friend request.
- User B opens his notifications tab and sees the request and does nothing.
- User A navigates to the sent requests tap and cancels the request.
- User A navigates to the explore tab and send the request again.
- Then User B test to behaviors:
1. User B press the blue link called Friend request from the old notification before refreshing.
2. User B refreshes the notification page first, then press the link.

In both cases, no issues occurred at all! Please let me know if I misunderstood your steps.

**Comment by Nazeh** [comment]
This issue was caused by the persistent of a notification after the deletion of the friendship that acted as notifiable for it, the latest changes in [pull/6](https://github.com/Nazeh/facebook-replica/tree/friendship-v2) solved that problem.
